### ISSUE TITLE
Increase number of displayed profiles on login screen.

### ISSUE THREAD

**Issue by HighTide** [NortheBridge/skin.arctic.zephyr.fromashes#17]
Currently the skin only shows 3 profiles on the login screen, I would prefer it if it would show more.

There is plenty of space left on the login screen. I think 4/5 would be more practical, however maybe a changeable number in the skin settings would also not hurt.

**Comment by NorthernLights** [comment]
We'll look into adding two additional spaces to the login screen for the **Autumn 2016 Update.** As Skin Settings is also being redone in the Autumn 2016 Update, an adjustable number for it simply isn't currently doable and has to be hard coded in.

**Comment by HighTide** [comment]
Oke, thanks 2 additional spaces would solve my annoyance.
